### ISSUE TITLE
Using centrifuge premade (.cf) database

### ISSUE THREAD

**Issue by benkraj** [khyox/recentrifuge#12]
Hi-

I'm looking to use recentrifuge with an existing pre-built nt centrifuge database (i.e. files nt.1.cf, nt.2.cf, nt.3.cf, and nt.4.cf). From [here](https://github.com/khyox/recentrifuge/wiki/Centrifuge-nt) you seem to point to being able to use this directly. Am I missing a step to get the .dmp files from this cf database?

Thanks,
Ben

**Comment by benkraj** [comment]
Also, I realize this seems similar to [this issue](https://github.com/khyox/recentrifuge/issues/4), but I wasn't able to resolve it directly based on that info.

**Comment by khyox** [comment]
Hi Ben,

- Short-answer: Just proceed following the installation instructions and use `retaxdump` as directed in the [installation instructions](https://github.com/khyox/recentrifuge/wiki/Installation#3-getting-the-databases).

- Long-answer: In case a custom Centrifuge database I suggest using the NCBI taxdump files that were used to build such database (or a more recent release). But, in case of a pre-built nt centrifuge database, I would use any recent version of the NCBI taxdump files. This includes the ones retrieved by `retaxdump` when you follow the Recentrifuge [installation instructions](https://github.com/khyox/recentrifuge/wiki/Installation#3-getting-the-databases). In case of an important mismatch between the contents of the NCBI taxdump databases used by the classifier and Recentrifuge, you will get warning messages in the console. Please read the [Troubleshooting section](https://github.com/khyox/recentrifuge/wiki/Troubleshooting) for details.

**Comment by benkraj** [comment]
Ok great. Thanks for your help Jose.

**Comment by benkraj** [comment]
Also as a note, I was having an issue with the retaxdump script.
`(centrifuge) [krajacichbj@cn3286 centrifugedb]$ python retaxdump

=-= retaxdump =-= v0.28.7 - Mar 2019 =-= by Jose Manuel Martí =-=

Downloading taxdmp.zip from NCBI FTP... PROBLEM!
 Retrying with HTTPS... OK!
Traceback (most recent call last):
  File "retaxdump", line 126, in <module>
    main()
  File "retaxdump", line 114, in main
    filezip = ZipFile(ZIPFILE)
  File "/data/krajacichbj/conda/envs/centrifuge/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/data/krajacichbj/conda/envs/centrifuge/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
`

I manually downloaded it from the linked ftp and just pointed the rcf -n to the files which made it work fine. It 100% may be an issue with my configuration, but thought I'd drop a note in case it's something else.

**Comment by khyox** [comment]
Hi Ben. Thanks for the feedback!
Regarding your last problem, I have tested `retaxdump` locally and also relaunched the Travis CI build for the last release (0.28.7), and all seem fine (https://travis-ci.org/khyox/recentrifuge/builds/503390908). I guess it could be an issue not related to Recentrifuge, perhaps some network trouble.
Thanks.
