### ISSUE TITLE
recentrifuge.rank.UnsupportedTaxLevelError: Unknown tax level section

### ISSUE THREAD

**Issue by oatesa** [khyox/recentrifuge#15]
# Bug report

### Bug summary

error running rcf similar to prev subcohort 
    f'Unknown tax level {_rank}') recentrifuge.rank.UnsupportedTaxLevelError: Unknown tax level section

Only works using old nodes&names

#### Command line

/home/recentrifuge/recentrifuge-master/rcf -f /home/600219/Classification/barcode01_classification.out -e FULL

```

#### Data

centrifuge classification.out file

### Actual outcome

<!--The output produced by the above code, which may be a screenshot, console output, etc.-->

File "/home/recentrifuge/recentrifuge-master/recentrifuge/taxonomy.py", line 40, in __init__
    self.read_nodes(nodes_file)
  File "/home/recentrifuge/recentrifuge-master/recentrifuge/taxonomy.py", line 82, in read_nodes
    f'Unknown tax level {_rank}')
recentrifuge.rank.UnsupportedTaxLevelError: Unknown tax level section

### Expected outcome

<!--If this used to work in an earlier version of Recentrifuge, please note the version it used to work on-->


### Versions 
<!--Please specify your platform and versions of the relevant libraries you are using:-->
  * Operating system:
  * Python version:
  * Recentrifuge version: 
  * Release of Centrifuge, LMAT, CLARK, Kraken, etc. (version used to generate the input data):
  * Pandas version (if applicable):
  * Other libraries (if applicable):

**Comment by khyox** [comment]
Hi @oatesa, 
Thank you for your bug report. That problem should be corrected since version v0.28.8 (April 11); the most current version is v0.28.10. Which version of recentrifuge are you using?
Thanks.

**Comment by oatesa** [comment]
Many thanks for getting back to me, we must have missed the update apologises for taking up you time. All working fine now, thank you for the swift response

Bw

Angela

**Comment by khyox** [comment]
Thank you for your feedback. I am closing the issue.
