### ISSUE TITLE
retest error: "remock: error: one of the arguments -m/--mock is required"

### ISSUE THREAD

**Issue by lkmklsmn** [khyox/recentrifuge#16]
# Bug report

### Bug summary

I am getting the following error when running retest:
![image](https://user-images.githubusercontent.com/11682947/60219373-cb1fe880-9837-11e9-80e5-14e11203847a.png)

And when I am running remock:
![image](https://user-images.githubusercontent.com/11682947/60219536-69ac4980-9838-11e9-8f19-3189c74b5080.png)

#### Command line

```
> retest
> remock -m recentrifuge/test/ -r 35 -d
```

#### Data

  * Format of input data (Centrifuge, LMAT, CLARK, Kraken, or other —generic interface—)?
  * If the generic interface was used, please provide some lines selected from the data files as a sample of the format:
  * Control samples (if any):
  * Regular samples:

### Actual outcome

```
# If applicable, paste the console output here
#
#
```

### Versions 

  * Operating system:
  * Python version:
  * Recentrifuge version: 
  * Release of Centrifuge, LMAT, CLARK, Kraken, etc. (version used to generate the input data):
  * Pandas version (if applicable):
  * Other libraries (if applicable):

**Comment by lkmklsmn** [comment]
Sorry. My mistake. I forgot to install openpyxl xlrd before running retest.

**Comment by khyox** [comment]
It makes sense! Thank you for the feedback.
