### ISSUE TITLE
Can command "rextract" support to extract reads from fasta files?

### ISSUE THREAD

**Issue by hansir8** [khyox/recentrifuge#19]
Thank you for this convenient software! 
I have used this software to investigate species taxonomy of assembled sequences. The command for centrifuge is 
"centrifuge -x $centrifuge_db -f 04.Assembly/trinity_denovo/Trinity.fasta \
-p 6 -S tmp/centrifuge_fa_result \
--report-file tmp/centrifuge_fa_report.tsv "

And i successfully obtained the html taxonomy by Recentrifuge software ("rcf" command), however, i can not extract according reads I wanted from fasta sequences using the command "rextract". I try many commands it provided:
"rextract -n $recentrifuge_taxa -i 10239 -f tmp/centrifuge_fa_result \
-1/-2/-q 04.Assembly/trinity_denovo/Trinity.fasta "

 I read the description about this command, and it can not support to extract sequences from fasta files . I am not familiar to python script. Can you add this function to this command? I am hoping that  you could solve this request i wanted. Thanks again.
Zhenzhi Han

**Comment by khyox** [comment]
Hi Zhenzhi,

Thanks for the feedback on Recentrifuge! I am glad that you find it useful for your analysis.

One of the foundations of Recentrifuge is the score or confidence level for every result. The taxonomic classifiers using the quality of the reads provided by the FASTQ format may provide more reliable results. That is the case of Centrifuge. Recentrifuge's goal is to ease (and encourage) the use of both confidence levels and controls. So, between FASTQ and FASTA, the election is clear.

Nevertheless, if you have currently a special case where only the FASTA files are available, you can use the [BBMaps's reformat](https://github.com/BioInfoTools/BBMap/blob/master/sh/reformat.sh) bash script to create FASTQ files with dummy quality values; for example:
`reformat.sh in=file_R1.fasta in2=file_R2.fastq out=file_R1.fastq out2=file_R2.fastq qfake=40`. That could be a very quick solution to your problem.

**Comment by hansir8** [comment]
Dear Manuel Martí:
    Thank you for quick reply. I have tried the  "BBMaps's reformat" bash script, and i already solved the question i requested. I convert the file format from  fasta to fastq, then extract the sequences i wanted. Finally, i also convert the fastq to fasta files that i needed. Thank you for your suggestion.
Zhenzhi Han

**Comment by khyox** [comment]
I am glad that you solved your issue and that you got your results. Thanks for the feedback. I am now closing this issue. If needed ¥, feel free to reopen (or open a new one for another issue).
