### ISSUE TITLE
The instructions for installing are extremely unclear

### ISSUE THREAD

**Issue by zmunro** [khyox/recentrifuge#25]
The instructions for how to install recentrifuge must be leaving a lot out.

I ran `python3.8 -m pip install recentrifuge`, then I installed all the dependencies the same way.
But `rcf` is not a command my computer can find.
What installation step is missing?

**Comment by khyox** [comment]
https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line
