### ISSUE TITLE
More than 10 mins on a centrifuge result (21.3 MB)

### ISSUE THREAD

**Issue by yeli7068** [khyox/recentrifuge#26]
Hi,

The latest version (v1.2.1) took more than 10 mins on a small result.
[ion_test.fq.zip](https://github.com/khyox/recentrifuge/files/5579825/ion_test.fq.zip)
The input was a centrifuge result as attached (21.3 MB after decompressing). 

Python: Python 3.6.10 :: Anaconda, Inc.
Centrifuge: 1.0.4
Hardware: CPU 24C/48T, 128 GB RAM. 

Thanks in advance for your helps.

**Comment by khyox** [comment]
It took exactly 20 seconds (of those, just 1.4 seconds loading the file) on my >1yo laptop with Python 3.8.3, so it should very probably be a local problem with your system/configuration. This is the output:

```
(...)
Loading output file /Users/user/Downloads/test/ion_test.fq.centri_out... OK!
  Seqs read: 430_839	[70.05 Mnt]
  Seqs clas: 419_293	(2.68% unclassified)
  Seqs pass: 419_293	(0.00% rejected)
  Scores: min = 23.0, max = 261.0, avr = 108.2
  Length: min = 30 nt, max = 365 nt, avr = 163 nt
  TaxIds: by classifier = 15, by filter = 15
Building from raw data with mintaxa = 6 ... 
  Check for more seqs lost ([in/ex]clude affects)... OK!
/Users/user/Downloads/test/ion_test.fq sample OK!
Load elapsed time: 1.39 sec


Building the taxonomy multiple tree... OK!
Generating final plot (GH_TEST.rcf.html)... OK!
Generating Excel full summary (GH_TEST.rcf.xlsx)... OK!
Total elapsed time: 00:00:20

Process finished with exit code 0
```

I would suggest you to talk to your system administrator so that he/she can be aware of the issue.
