### ISSUE TITLE
rextract: zipped fastq files

### ISSUE THREAD

**Issue by fancyge** [khyox/recentrifuge#30]
Hi, is it possible to add an option for taking zipped fastq files and outputing zipped files as well. This is useful when the data is too large. Thanks!!

**Comment by khyox** [comment]
Hi @fancyge, thanks for the enhancement suggestion. For processing kraken output you have already the option to taking compressed files (see [Kraken: use of compressed files](https://github.com/khyox/recentrifuge/wiki/Running-recentrifuge-for-Kraken#use-of-compressed-files)). Which output files are you thinking of? Thanks.

**Comment by fancyge** [comment]
Hi, thanks a lot for the quick response! I have already got the centrifuge classification files and want to run rextract to filter the reads. I noticed that rextract can only take fastq file but will go wrong with "fastq.gz" file. I prefer "fastq.gz" for storage saving purpose.

I also want to ask about the "multiple -i " option in rextract for listing several taxid. Can you show me how to exactly put these into commands? I used the following but not going through: "rextract -f my_classification_results.txt multiple -i 9606 452 -1 R1.fq -2 R2.fq".

Thank you.

**Comment by khyox** [comment]
OK, I see, it is about `rextract`. The issue #28 is also an enhancement suggestion, so I will probably address both of them soon.

About the `-i` option, you have to prepend any taxid to include with such a flag. In your case:
```
rextract -f my_classification_results.txt multiple -i 9606 -i 452 -1 R1.fq -2 R2.fq
```

**Comment by fancyge** [comment]
Thanks! Hope to see it soon! Quite useful tools!
By the way, do you have an idea what score (-y) I should feed to rextract for filtering centrifuge results? I have 150bp fastq files from illumina sequencing.

**Comment by fancyge** [comment]
I just added some commands to make it possible to take&output zipped fastq files. It might not be ideal but can be used at the moment. Thanks.

[rextract.py.zip](https://github.com/khyox/recentrifuge/files/6159554/rextract.py.zip)

**Comment by khyox** [comment]
> By the way, do you have an idea what score (-y) I should feed to rextract for filtering centrifuge results? I have 150bp fastq files from illumina sequencing.

My recommendation is to avoid too low `minscore` (`-y` flag also) values to filter sequences with low scores. Also, if you have control sequences, you may want to lower `ctrlminscore` (`-z` flag also) to have more sequences in the controls and thus more sequences removed after the robust control removal algorithm. So, --minscore 35 and --ctrlminscore 25 could be good values to start with.

**Comment by khyox** [comment]
> I just added some commands to make it possible to take&output zipped fastq files. It might not be ideal but can be used at the moment. Thanks.
> 
> [rextract.py.zip](https://github.com/khyox/recentrifuge/files/6159554/rextract.py.zip)

Thanks! If you open a PR I'd happy to check it and include it in the master branch.
