### ISSUE TITLE
centrifuge db

### ISSUE THREAD

**Issue by shlomobl** [khyox/recentrifuge#4]
Hi,

How may I use for recentrifuge the same libraries/db that I already downloaded for centrifuge?

Thanks!

**Comment by khyox** [comment]
Recentrifuge only needs to know the path of the NCBI nodes information files (`nodes.dmp` and
`names.dmp`) that were used when the Centrifuge DB was created, but any newer release of these files should also work fine. You can indicate such path to Recentrifuge by the flag `-n PATH` or `--nodespath PATH`. Alternatively, you can execute `retaxdump.py`. It will download and unzip the required local databases from NCBI servers under the subdirectory `taxdump`.

**Comment by shlomobl** [comment]
Thanks. What about the sequences themselves. I downloaded the prebuilt indexes for nt dabatase from the Centrifuge site. Can I use this file too?

**Comment by khyox** [comment]
Sure! Recentrifuge will read the Centrifuge output, independently of the DB that you use for the taxonomic classification. Just follow the instructions in [the wiki](https://github.com/khyox/recentrifuge/wiki/Running-recentrifuge-for-Centrifuge).

**Comment by khyox** [comment]
I am closing this. Please reopen if there are further related questions.
