### ISSUE TITLE
(question) produced output 

### ISSUE THREAD

**Issue by arz19893** [khyox/recentrifuge#43]
Hi@khyox

I used the tool for Kraken files.  after downloading the tools, here is my follow the command 

to my cuurent direcity 

$ retaxdump 

$ rcf -k CRTL1.kraken -k abudl_testextract_barcode26.kraken -c 1 -o Xsamples.rcf.html -s KRAKEN -y 25 -x 9606

following the output and reading the instruction, I observe that the confidence level is increased (from the chart link) but wondering 

is that mean any organism present in control will be discarded in samples? but what if the sample has the discarded organism (not from contamination) ? , in the excel produced file,  is there an option I can see which organism is selected for filtering? 

following the output, I see you can choose either CSV, FULL, etc Can I produce Kraken report.txt file as well for each sample?  

Thank you for the help 

<img width="454" alt="Screenshot 2022-05-31 at 14 22 39" src="https://user-images.githubusercontent.com/65975305/171183530-239b523d-9f3f-445a-ad4d-96132ba5280e.png">

**Comment by khyox** [comment]
Hi @arz19893,

About your first question, in general, most of the organisms present in the negative controls are removed from the regular samples, but the final outcome depends on your particular case. The robust contamination removal method in Recentrifuge is explained in [this subsection](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006967#sec008) of the [paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006967). You can find further details in the wiki section "[Understanding the messages of the robust contamination removal algorithm](https://github.com/khyox/recentrifuge/wiki/Testing-and-more#understanding-the-messages-of-the-robust-contamination-removal-algorithm)". 

About your second question, I am not sure that I completely understand it, but the documentation that I referred above should help with this too. Recentrifuge is able to detect some kind of cross-contamination, even from regular samples to the controls. In case you have only one negative control and the organisms is quite abundant both in this sample and in the regular ones, it will be removed. If a native organism in the regular samples has introduced an important contamination on the negative controls, then the experimental procedure is flawed with severe cross-contamination to the point that the "negative controls" cannot be considered so anymore. In other cases, you can fine tune some parameters of the filters in Recentrifuge, see for example [this comment](https://github.com/khyox/recentrifuge/issues/40#issuecomment-1113928399).

Regarding your 3rd question: No, the tabulated output (including the excel files) is not giving detailed information for the contamination removal, but you can see the logs, which provide with all the details with the aid of colored output for identifying the kind of contamination, as explained in the wiki section "[Understanding the messages of the robust contamination removal algorithm](https://github.com/khyox/recentrifuge/wiki/Testing-and-more#understanding-the-messages-of-the-robust-contamination-removal-algorithm)". In #40, it was suggested that to provide, optional, separate output (beyond the console log) devoted to the contamination removal algorithm would be a welcomed addition.

Finally, about your last question, there is no option on Recentrifuge to provide Kraken's report file. While Recentrifuge supports Kraken and other classifiers, its most complete support is for the [Centrifuge classifier](http://www.ccb.jhu.edu/software/centrifuge/) (hence its name).
