### ISSUE TITLE
Excel output with empty columns

### ISSUE THREAD

**Issue by blwe** [khyox/recentrifuge#8]
Hi there! Thank you very much for recentrifuge, the HTML output is incredible useful! However, I have a problem with the Excel output. It has empty columns everywhere. Could you check it, please? Thanks a lot!

**Comment by khyox** [comment]
Hi @blwe! 
Thank you very much for reporting this issue! I think I have reproduced the problem you have found. The source of the bug was a change in naming the derivate samples some releases ago. I will come back with a solution soon and let you know. 
Thanks!

**Comment by khyox** [comment]
OK, the issue is solved in 8d8cfb69e65727962ab2f12f0ddb3ab32c7adae4. The problem was limited to the `cmplxCruncher` Excel output, not the `full` (default) Excel output. Could you confirm that this was your case? Thanks for reporting!

**Comment by blwe** [comment]
Yeah, that was exactly my case! It's working now! Thanks for the quick solution!!

**Comment by my-serendipity** [comment]
For me it would be very useful to have plain csv output instead of the excel one!

**Comment by khyox** [comment]
Hi. Could you please open an issue for that feature request? Thanks!

**Comment by my-serendipity** [comment]
Sure!
