### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by my-serendipity** [khyox/recentrifuge#9]
Thanks for Recentrifuge! It would be nice to have cvs output as an alternative to the excel output. Any plans on this?

**Comment by khyox** [comment]
In 5a67a4f6e4129f334c15a75f0e06c9638ade8565, I added support for CSV and TSV formats in the extra output files generated by Recentrifuge. Enjoy!

**Comment by my-serendipity** [comment]
Wow! so fast! thank you!!
